version: '3'
services:
    web:
        image: allanfvc/uni7sum
        ports: 
            - "8081:8080"
        environment:
            - OTHER_ENDPOINT=http://jprubio:80/api/sum
    jprubio:
        image: "jprubio/myapp:20200808083225"