apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: allanfvc
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: allanfvc/uni7sum:1.1.0
        ports:
        - name: myapp-port
          containerPort: 8080